# Generated by Django 4.1.3 on 2022-12-22 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Particle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_count', models.PositiveSmallIntegerField()),
                ('flow', models.PositiveSmallIntegerField()),
                ('group', models.PositiveSmallIntegerField()),
                ('course', models.PositiveSmallIntegerField(default=1)),
                ('semester', models.PositiveSmallIntegerField(default=2)),
                ('lecture', models.PositiveSmallIntegerField(default=30)),
                ('practice', models.PositiveSmallIntegerField(default=30)),
                ('laboratory', models.PositiveSmallIntegerField(default=0)),
                ('seminar', models.PositiveSmallIntegerField(default=0)),
                ('coursework', models.PositiveSmallIntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language')),
                ('majors', models.ManyToManyField(related_name='particle_majors', to='main.major')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Particle_Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_count', models.PositiveSmallIntegerField()),
                ('flow', models.PositiveSmallIntegerField()),
                ('group', models.PositiveSmallIntegerField()),
                ('semester', models.PositiveSmallIntegerField()),
                ('lecture', models.PositiveSmallIntegerField(default=0)),
                ('practice', models.PositiveSmallIntegerField(default=0)),
                ('laboratory', models.PositiveSmallIntegerField(default=0)),
                ('seminar', models.PositiveSmallIntegerField(default=0)),
                ('coursework', models.PositiveSmallIntegerField(default=0)),
                ('raiting', models.PositiveSmallIntegerField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language')),
                ('particle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='main.particle')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='particle',
            name='science',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.science'),
        ),
    ]
